language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  api_key:
    secure: Uy6tyPP28AbKd0yzfoSqMzhrmXHVLdIFPxqOYh/NqFG5ZqEjYol77//aH5iK35xTffFdfAVJirRe/20SK5wk8OPJhDX2+4lnuQYqc2OvIUm59ljhJvbSpZp7lOoonfu/vjq/DPTmqoUqxizFg0Nb9Ld2pLI/15P3tyAlvKeOscKKcXBZIj2lgv1PQK0skqWB+l5SGOG0trUWnC6sZEY56zyS34phi/g/Er7b4enA+rx+j52AfjNtWZhUlz1YRsqyxj2K/k+x6LI6/L4Xo8LXKPVjtbFY2ErFqq/gIDkHD34NHp8jhNlnUSQKEFkFyQ3iZVo20UOs6JsMlGgXWiTcMAAbUQoJoSZ7y6YtV1jTvNnY53qNxM/3JWfkeb87A/Rz9JdMZwONb2qn3od95xZm85SmQ0clyO2MOySU/WXQWc24s+gk9lKYFPkPwApBtmXeaT9J3lF2RwjdL3krVHc4I/9a5BDcybeXHOLVQm5YvrbiWW+Vf+2oveMzeYZULZC77PUNWN22/OvQ6KIlfzhKC8lq2Yg3GU/RCxDMpm5G9J1nc9Ig7BjqPd7RyNUYsMFJ1wvh3FJXqBqIy5U0hXLLUGoy97uRZYcWK4llZ04B8lcvPeXmSJCIHEPvkTfixEpjt1y1AAv28yf661oS4stocGz2aLkTUYNEA90SPfkdyJk=
  app: JAlgoArena-Eureka
  on:
    repo: pszewczy/JAlgoArena-Eureka
