language: Java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_deploy:
- "./gradlew releaseZip"
deploy:
  provider: heroku
  api_key:
    secure: LBxrP0jZz6ZEocbBMmLRitLPduC5jv11Q3cH2y/kmJInsUFQ+zOf0woffe6plK0vtXn1PhJPNZnFWQ4MPK6zSuqSXKzRe3COGA7cYlkr7zq0uxvi08hmt2QNU2G+6947XauE6irRLwqvoEiW+dzJaJ6wSTZ6hOetO687Jv6SoqfWKWVLfCXL598saKbwsIZvQY4L8zskZcqdpha8uAVqDTyU3F+9ynW2aB1W7i8nlrrb6eLoIziHEEQzzct4qLbhrjZd2ipuLSh1nUo0EtNMRgVFLvUrhjnmDTJReqS5C0LlXqpuR8cLNcIwU6MvFgPg+r17HAzTJjLfmZ29Wom+9JhLslwZSqvfLg3qbyqvYAiqkLzgyV97VQX7w/9w2T+P1uaIcRP7SiPAFZ6HQCZ3SsV7vdCVb+f2/i328WyTaKX7rSIGAJ7Ov68Y4o3cSBNSPRUTqWuO070f2yLTSH/t4u58+wj8aGItxm+zjjF9W3opyQcB01b8Bwxn1Eq/KlgBzvdkhSApsnVXsJo6eEu5IVYRyguS3Kt0SYSdqHLxsni7XGYBH9IsrWHpbnusatBqohymO/cPDLuG2Oq1fa/UZApYDKHlLU0emTUrm3AErQKPVl+w1cy5pd81YpHVYLIi5mg0YgOODUXfh0J8dSM0Ok96ZvNKjEQEMLZaKa2Fb5A=
  app: JAlgoArena-Eureka
  on:
    repo: pszewczy/JAlgoArena-Eureka
